version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '7050:3306'
    environment:
       MYSQL_DATABASE: 'poketch_db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'poketch_secret'
       MYSQL_ROOT_PASSWORD: 'poketch_secret'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/poketch
    ports:
      - "8000:8000"
    depends_on:
      - db