# Generated by Django 3.2 on 2021-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('gen', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('image_link', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('catched', models.CharField(max_length=255)),
                ('tcg_owned', models.CharField(max_length=255)),
            ],
        ),
    ]
