# Generated by Django 3.2 on 2021-04-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketch_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='link',
            new_name='article_link',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='catched',
            new_name='console_owned',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='gen',
            new_name='generation',
        ),
        migrations.CreateModel(
            name='RegionalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField()),
                ('generation', models.IntegerField()),
                ('image_link', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('console_owned', models.CharField(max_length=255)),
                ('tcg_owned', models.CharField(max_length=255)),
                ('normal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketch_app.pokemon')),
            ],
        ),
    ]
