# Generated by Django 3.2 on 2021-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketch_app', '0002_auto_20210406_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalFormPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('generation', models.IntegerField()),
                ('article_link', models.CharField(max_length=255)),
                ('image_link', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('console_owned', models.CharField(max_length=255)),
                ('tcg_owned', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RegionalForm',
        ),
    ]
