# Generated by Django 3.2 on 2021-04-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poketch_app', '0003_auto_20210406_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='tcg_owned',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='regionalformpokemon',
            old_name='tcg_owned',
            new_name='note',
        ),
    ]
